var MONTH_NAMES=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];var pluralize=(t,e)=>`${t} ${e}${t<=1?"":"s"}`;function getTooltip(t,e){const o=new Date(e.getTime()-e.getTimezoneOffset()*6e4).toISOString().split("T")[0];if(t.count===0){return`No writing on ${o}`}const n=pluralize(t.post,"post");const a=pluralize(t.count,"word");return`${n} ${a} on ${o}`}var heatmapTooltip=document.getElementById("heatmap-tooltip");function hideTooltip(){heatmapTooltip.style.display="none"}function tileClickHandler(t){const o=t.target;if(!o.classList.contains("tile"))return;const e=new Date(Number(o.dataset.date));const n=e.toISOString();const a=window.REIMU_HEATMAP_CONFIG.articleStats.filter(t=>t.date===n);const l=o.dataset.level;const i=e.toLocaleDateString();let c=0;let s=`
    <div class="tooltip-header">
      <div class="tooltip-header-content">${i} (Level ${l})</div>
      <div class="popup-btn-close tooltip-close"></div>
    </div>
    <div class="tooltip-content">
      <ul>
  `;const r=window.REIMU_HEATMAP_CONFIG.i18n;let d=document.documentElement.lang||"en";if(!Object.keys(r).includes(d)){d="en"}if(a.length===0){s+=`<li>${r[d].no_articles}</li>`}else{a.forEach(t=>{c+=t.wordcount;s+=`<li><a href="${t.url}">${t.title}</a> (${t.wordcount} ${r[d].words})</li>`})}const p=r[d].total_articles.replace("$1",a.length).replace("$2",c);s+=`
      </ul>
      <div class="tooltip-footer">
        ${p}
      </div>
    </div>
  `;heatmapTooltip.innerHTML=s;const u=o.getBoundingClientRect();heatmapTooltip.style.display="block";heatmapTooltip.style.visibility="hidden";heatmapTooltip.style.left="0px";const m=heatmapTooltip.getBoundingClientRect();const v=m.width;let g=u.right+10;if(g+v>window.innerWidth){g=u.left-v-10}heatmapTooltip.style.left=`${g}px`;heatmapTooltip.style.top=`${u.top}px`;heatmapTooltip.style.display="block";heatmapTooltip.style.visibility="visible";const f=heatmapTooltip.querySelector(".tooltip-close");if(f){f.addEventListener("click",hideTooltip)}document.addEventListener("click",function t(e){if(e.target.classList.contains("tile")){return}if(!heatmapTooltip.contains(e.target)&&e.target!==o){hideTooltip();document.removeEventListener("click",t)}})}function createCalendar(e,t){if(!e){return}e.innerHTML=`
    <div class="outer-box">
      <div class="year-select"></div>
      <div class="inner-box">
        <div class="calendar-container">
          ${["Mon","Wed","Fri"].map(t=>`<span class="week">${t}</span>`).join("")}
          <div class="legend">Less${new Array(5).fill(0).map((t,e)=>`<i class="tile" data-level="${e}"></i>`).join("")}More</div>
          <div class="tiles"></div>
        </div>
      </div>
    </div>
  `;const l=e.querySelector(".calendar-container");const o=e.querySelector(".year-select");const i=e.querySelector(".tiles");const c=completeContributionData(t);const n=(new Date).getFullYear();o.innerHTML=Object.keys(c).sort((t,e)=>e-t).map(t=>`<div class="year-option ${t==n?"active":""}">${t}</div>`).join("");o.addEventListener("click",({target:t})=>{if(t.classList.contains("year-option")){e.querySelector(".active")?.classList.remove("active");t.classList.add("active");a(t.textContent)}});const a=t=>{i.innerHTML="";l.querySelectorAll(".month").forEach(t=>t.remove());l.querySelectorAll(".total").forEach(t=>t.remove());const e=c[t];const s=new Date(e[0].date).getDay();let r=-1;const d=document.createDocumentFragment();const o=document.createDocumentFragment();let p=-1;const[n,a]=e.reduce(([t,e],o,n)=>{const a=new Date(o.date);const l=a.getMonth();e.count+=o.count;e.post+=o.post;if(a.getDay()===0&&l!==r){let t=2+Math.floor((n+s)/7);if(t-p<=1){t+=2-t+p}p=t;r=l;const c=document.createElement("span");c.className="month";c.textContent=MONTH_NAMES[l];c.style.gridColumn=t;d.append(c)}const i=document.createElement("i");i.className="tile";i.dataset.level=o.level;i.title=getTooltip(o,a);i.dataset.level=o.level;i.dataset.date=o.date;i.addEventListener("click",tileClickHandler);t.push(i);return[t,e]},[[],{count:0,post:0}]);if(n[0]){n[0].style.gridRow=s+1}o.append(...n);l.append(d);i.append(o);l.insertAdjacentHTML("beforeend",`<div class="total">${pluralize(a.post,"post")} ${pluralize(a.count,"word")} in ${t}</div>`)};a(n)}function completeContributionData(t){t.sort((t,e)=>t.date-e.date);const e=new Date(t[0].date);const o=new Date;const n={};const a={};t.forEach(t=>{const e=new Date(t.date);const o=`${e.getFullYear()}-${e.getMonth()}-${e.getDate()}`;a[o]=t});for(let t=e.getFullYear();t<=o.getFullYear();t++){const[l,i]=t===o.getFullYear()?[new Date(new Date(o).setDate(o.getDate()-365)),new Date(o.getTime()+864e5)]:[new Date(t,0,1),new Date(t+1,0,1)];const c=[];for(let t=l;t<i;t.setDate(t.getDate()+1)){const s=`${t.getFullYear()}-${t.getMonth()}-${t.getDate()}`;c.push(a[s]||{level:0,date:t.getTime(),count:0,post:0})}n[t]=c}return n}function getLevelFromWordCount(t){const e=window.REIMU_HEATMAP_CONFIG.levelStandard.split(",").map(Number);if(t<=0)return 0;if(t<=e[0])return 1;if(t<=e[1])return 2;if(t<=e[2])return 3;return 4}var currentDate=new Date;function transformArticlesData(t){const e=t.reduce((t,{date:e,wordcount:o})=>{if(new Date(e)>currentDate){return t}const n=t.get(e)??{count:0,post:0};return t.set(e,{count:n.count+o,post:n.post+1})},new Map);return Array.from(e,([t,{count:e,post:o}])=>({level:getLevelFromWordCount(e),date:new Date(t).getTime(),count:e,post:o}))}createCalendar(document.querySelector("#heatmap"),transformArticlesData(window.REIMU_HEATMAP_CONFIG.articleStats));