(()=>{_$$("pre").forEach(e=>{const o=e.parentNode;if(!o.classList.contains("gutter")){const t=document.createElement("div");t.className="code-area";o.replaceChild(t,e);t.appendChild(e)}});const i=`
  <div class="code-figcaption">
    <div class="code-left-wrap">
      <div class="code-decoration"></div>
      <div class="code-lang"></div>
    </div>
    <div class="code-right-wrap">
      <div class="code-copy icon-copy"></div>
      <div class="icon-chevron-down code-expand"></div>
    </div>
  </div>`;const e=window.REIMU_CONFIG?.code_block||{};const s=e.expand;_$$("figure.highlight").forEach(e=>{if(!e.querySelector(".code-figcaption")){e.insertAdjacentHTML("afterbegin",i)}if(s!==undefined){if(s===false||typeof s==="number"&&e.querySelectorAll("td.code .line").length>s){e.classList.add("code-closed");e.style.display="none";void e.offsetWidth;e.style.display=""}}const o=e.className.split(" ")[1];if(o){const t=o.replace("line-numbers","").replace("language-","").trim().toUpperCase();const c=e.querySelector(".code-lang");if(c)c.innerText=t}});_$$(".code-expand").forEach(e=>{e.off("click").on("click",()=>{e.closest("figure")?.classList.toggle("code-closed")})});if(!window.ClipboardJS){return}const c=window.REIMU_CONFIG?.clipboard_tips||{};const t=(e,o)=>{if(typeof e==="string")return e;if(typeof e==="object"){const t=document.documentElement.lang.toLowerCase();const c=Object.keys(e).find(e=>e.toLowerCase()===t);if(c&&e[c])return e[c]}return o};const o=new ClipboardJS(".code-copy",{text:e=>{const o=e.parentNode.parentNode.parentNode.querySelector("td.code");let t=o?.innerText||"";if(c.copyright?.enable&&t.length>=c.copyright?.count){t+="\n\n"+(c.copyright?.content??"")}return t}});o.on("success",e=>{e.trigger.classList.add("icon-check");e.trigger.classList.remove("icon-copy");const o=t(c.success,"Copy successfully (*^▽^*)");_$("#copy-tooltip").innerText=o;_$("#copy-tooltip").style.opacity=1;setTimeout(()=>{_$("#copy-tooltip").style.opacity=0;e.trigger.classList.add("icon-copy");e.trigger.classList.remove("icon-check")},1e3);e.clearSelection()});o.on("error",e=>{e.trigger.classList.add("icon-times");e.trigger.classList.remove("icon-copy");const o=t(c.fail,"Copy failed (ﾟ⊿ﾟ)ﾂ");_$("#copy-tooltip").innerText=o;_$("#copy-tooltip").style.opacity=1;setTimeout(()=>{_$("#copy-tooltip").style.opacity=0;e.trigger.classList.add("icon-copy");e.trigger.classList.remove("icon-times")},1e3)});if(window.Pjax){window.addEventListener("pjax:send",()=>{o.destroy()},{once:true})}window.AOS?.refresh()})();